//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RstegApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RstegApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе {0}.
        /// </summary>
        internal static string AboutTemplate {
            get {
                return ResourceManager.GetString("AboutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗНТУ - РТ-812.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The calling application does not have Administrator privileges..
        /// </summary>
        internal static string ApplicationNotHavePrivilegesMessage {
            get {
                return ResourceManager.GetString("ApplicationNotHavePrivilegesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стего модуль.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ передан. Инициализация сброса пакетов..
        /// </summary>
        internal static string DropPacketInitializeMessage {
            get {
                return ResourceManager.GetString("DropPacketInitializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на skyskryn@gmail.com.
        /// </summary>
        internal static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец.
        /// </summary>
        internal static string EndMessage {
            get {
                return ResourceManager.GetString("EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исключение: {0}..
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This indicates an invalid packet filter string, layer, priority, or flags..
        /// </summary>
        internal static string InvalidWinDivertPropertiesMessage {
            get {
                return ResourceManager.GetString("InvalidWinDivertPropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP адрес:.
        /// </summary>
        internal static string IPField {
            get {
                return ResourceManager.GetString("IPField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _key.
        /// </summary>
        internal static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение:.
        /// </summary>
        internal static string MessageField {
            get {
                return ResourceManager.GetString("MessageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено сообщение: .
        /// </summary>
        internal static string MessageRecieved {
            get {
                return ResourceManager.GetString("MessageRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлено сообщение:.
        /// </summary>
        internal static string MessageSended {
            get {
                return ResourceManager.GetString("MessageSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not a valid IPV4 address..
        /// </summary>
        internal static string NotValidIp4AddressException {
            get {
                return ResourceManager.GetString("NotValidIp4AddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not a valid IPV6 address..
        /// </summary>
        internal static string NotValidIp6AddressException {
            get {
                return ResourceManager.GetString("NotValidIp6AddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK..
        /// </summary>
        internal static string OkMessage {
            get {
                return ResourceManager.GetString("OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывод.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт:.
        /// </summary>
        internal static string PortField {
            get {
                return ResourceManager.GetString("PortField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передать ключ.
        /// </summary>
        internal static string SendKeyWord {
            get {
                return ResourceManager.GetString("SendKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправка легальных данных....
        /// </summary>
        internal static string SendLegalDataMessage {
            get {
                return ResourceManager.GetString("SendLegalDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно отправить пакет..
        /// </summary>
        internal static string SendPacketError {
            get {
                return ResourceManager.GetString("SendPacketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применение стеганографии к пакету..
        /// </summary>
        internal static string StegonographyAddedMessage {
            get {
                return ResourceManager.GetString("StegonographyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ найден. К следующему сообщение будет применена стеганография..
        /// </summary>
        internal static string StegonographyInitializeMessage {
            get {
                return ResourceManager.GetString("StegonographyInitializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _steg.
        /// </summary>
        internal static string StegWord {
            get {
                return ResourceManager.GetString("StegWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tcp.DstPort == {0}.
        /// </summary>
        internal static string Template_DestinationFilter {
            get {
                return ResourceManager.GetString("Template_DestinationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пакет отклонен. Осталось: {0}..
        /// </summary>
        internal static string Template_DropPacket {
            get {
                return ResourceManager.GetString("Template_DropPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} .
        /// </summary>
        internal static string Template_MessageType {
            get {
                return ResourceManager.GetString("Template_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tcp.SrcPort == {0}.
        /// </summary>
        internal static string Template_PacketFilter {
            get {
                return ResourceManager.GetString("Template_PacketFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия {0}.
        /// </summary>
        internal static string Template_Version {
            get {
                return ResourceManager.GetString("Template_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The WinDivert driver is blocked by security software or you are using a virtualization environment that does not support drivers..
        /// </summary>
        internal static string WinDivertDriverBlockedMessage {
            get {
                return ResourceManager.GetString("WinDivertDriverBlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The WinDivert32.sys or WinDivert64.sys driver does not have a valid digital signature.
        /// </summary>
        internal static string WinDivertDriverSignatureNotValidMessage {
            get {
                return ResourceManager.GetString("WinDivertDriverSignatureNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The driver files WinDivert32.sys or WinDivert64.sys were not found..
        /// </summary>
        internal static string WinDivertSysNotFoundMessage {
            get {
                return ResourceManager.GetString("WinDivertSysNotFoundMessage", resourceCulture);
            }
        }
    }
}
